// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatisticsAssignment.Db;

#nullable disable

namespace StatisticsAssignment.Db.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    [Migration("20221224154248_ColumnNamesChanged")]
    partial class ColumnNamesChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StatisticsAssignment.Db.Entities.CountryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageAnnualHoursWorkedByPersonsEngaged")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("avh");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<decimal>("Population")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pop");

                    b.Property<decimal>("RealGdp")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rgdpna");

                    b.Property<decimal>("ShareOfHouseholdConsumption")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("csh_c");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("CountryData");
                });
#pragma warning restore 612, 618
        }
    }
}
